
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using Assets.Scripts;

namespace AssemblyCSharp
{
	public class Spell_Fireball : Spell
	{
		public Spell_Fireball ()
            // Level, damage, distance, text, speed, element
			: base(1, 5, 60, "Steek 1 vinger uit en draai deze in een cirkelvorm naar rechts.", 15, Element.Fire)
		{
			this.visuals = Resources.Load<GameObject>("FireBall");
			this.particle = new SpellParticle(visuals, this.spellDistance, 15);
		}
	}
}

