//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class SpellParticle
	{
		private GameObject particle;
		private float distance;
		private float speed;
		private float moved;

		public SpellParticle (GameObject particle, float distance, float speed)
		{
			this.particle = particle;
			this.distance = distance;
			this.speed = speed;

			moved = 0;
		}

		public float getDistance()
		{
			return distance;
		}

		public float getSpeed()
		{
			return speed;
		}

		public float getDistanceMoved()
		{
			return moved;
		}

		public void setMoved(float distance)
		{
			this.moved += distance;
		}

		public void setParticle(GameObject o)
		{
			particle = o;
		}

		public GameObject getParticle()
		{
			return particle;
		}
	}
}